# Generated by Django 6.0.3 on 2026-03-29 08:03

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=reports.models.generate_tracking_number, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('water', 'Water'), ('sewage', 'Sewage'), ('roads', 'Roads'), ('electricity', 'Electricity'), ('vandalism', 'Vandalism'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report_photos/')),
                ('location', models.CharField(max_length=255)),
                ('ward', models.CharField(choices=[('ikhutseng', 'Ikhutseng'), ('warrenton_cbd', 'Warrenton CBD'), ('surrounding', 'Surrounding Areas')], default='warrenton_cbd', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('resident_name', models.CharField(max_length=100)),
                ('resident_phone', models.CharField(max_length=20)),
                ('resident_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
