# Generated by Django 6.0.3 on 2026-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ward',
            field=models.CharField(choices=[('warrenton', 'Warrenton'), ('ikhutseng', 'Ikhutseng Location'), ('stasie', 'Stasie'), ('warrenvale', 'Warrenvale'), ('14_streams', '14 Streams')], default='warrenton', max_length=20),
        ),
    ]
